version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      monitoring:
        aliases:
             - influxdb
    volumes:
      - influxdb-volume:/var/lib/influxdb
  nodered:
    build: .
    container_name: mynodered
    restart: always
    ports:
      - "1880:1880"
    networks:
      - monitoring
    volumes:
      - nodered-volume:/data

networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  nodered-volume:
    external: true